### ISSUE TITLE
Crash when initializing the module

### ISSUE THREAD

**Issue by edhelas** [erigones/ludolph-chatbot#1]
I've been playing with Ludolph for a few days now and I'm really impressed by the quality of the project, thanks already for the wonderful work.

However I wasn't able to init this module properly on my server.

```
2017-07-25 18:31:20,774 INFO     ludolph.bot: Post-initializing plugin: ludolph_chatbot.chatterbot
2017-07-25 18:31:20,777 ERROR    ludolph.utils: No module named storage
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/ludolph/utils.py", line 40, in wrap
    return fun(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/ludolph/bot.py", line 416, in _post_init_plugin
    plugin_obj.__post_init__()
  File "/usr/local/lib/python2.7/dist-packages/ludolph_chatbot/chatterbot.py", line 48, in __post_init__
    **config
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/chatterbot.py", line 32, in __init__
    utils.validate_adapter_class(storage_adapter, StorageAdapter)
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils.py", line 63, in validate_adapter_class
    if not issubclass(import_module(validate_class), adapter_class):
  File "/usr/local/lib/python2.7/dist-packages/chatterbot/utils.py", line 15, in import_module
    module = importlib.import_module(module_path)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named storage
2017-07-25 18:31:20,778 ERROR    ludolph.utils: Got exception when running _post_init_plugin((<ludolph.bot.LudolphBot object at 0x7f2890df9c10>, 'ludolph_chatbot.chatterbot', <LudolphPlugin: ludolph_chatbot.chatterbot.Chatterbot>), {}): No module named storage.
```

There's maybe something missing in the configuration.

**Comment by dn0** [comment]
Thanks for the feedback :)

You're right. The *ludolph-chatbot* plugin is currently unmaintained and it does not work with the latest version of chatterbot.

The chatterbot API has probably changed - I will look into it...

**Comment by ricco386** [comment]
In the mean time chatterbot updated its file structure, so we needed to update the imports in order to be able to start the plugin.

Chatterbot should be working properly now. I have really quickly tested and it seems to be working, so I am closing this issue. If you find anything else do not hesitate to re-open or let us know by opening different issue.

Thanks.
